### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by himself65** [himself65/refine#42]
## Core

- [ ] stable data migration logic
- [ ] support sync with multiple servers

## Web

- [ ] Partial SSR in shared page
